run:
  skip-files:
    - ".*_test.go"
linters:
  enable:
    - godot
    - misspell
    - gocognit
    - funlen
  disable:
    - typecheck
linters-settings:
  staticcheck:
    checks: ["all", "-SA1019"]