---@meta

---FightState represents the current state of the fight in regard to the deck of the player.
---@class fight_state
---@field round number
---@field description string
---@field current_points number
---@field deck string[]
---@field hand string[]
---@field used string[]
---@field exhausted string[]