on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    permissions: write-all
    name: release linux/amd64
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_command: "apt-get update && apt-get install --no-install-recommends -y pkg-config libasound2-dev libx11-dev"
          project_path: "./cmd/game"
          binary_name: "end_of_eden"
          extra_files: "./assets/"
          goos: linux
          goarch: amd64
  release-windows-amd64:
    permissions: write-all
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_path: "./cmd/game"
          binary_name: "end_of_eden"
          extra_files: "./assets/"
          goos: windows
          goarch: amd64
  release-macos-amd64:
    permissions: write-all
    name: release macos/amd64
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
      - name: Build
        run: |
             cd cmd/game & go build -o end_of_eden
             export BIN=end_of_eden-$(basename ${GITHUB_REF})-macos-amd64
             mkdir $BIN
             cp ./end_of_eden $BIN/end_of_eden
             cp -r ../../assets $BIN/assets/
             zip -r $BIN.zip $BIN
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: end_of_eden-${{ github.ref_name }}-macos-amd64.zip